In [1]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [2]:
import pandas as pd

In [3]:
characters_data = pd.read_csv('/content/drive/MyDrive/characters_ani.csv')
anime_data = pd.read_csv('/content/drive/MyDrive/anime.csv')

In [4]:
characters_data.head()

,Unnamed: 0,ID,Name,Alias,Gender,Hair Color,Love Rank,Hate Rank,Eye color,Birthday,Blood Type,Tags,Love Count,Hate Count,Description,url,Counts,MAL_ID
0,0,0,L,Ryuzaki,Male,Black,1.0,48.0,Black,"October 31, 1979",Unknown,"Analytical, Barefoot, Detectives, Eye Bags, Sw...",44829,3447,"Secretive, meticulous and cunning, L's desire ...",https://www.anime-planet.com/characters/l-deat...,48276.0,1535.0
1,98,98,Kakashi HATAKE,"Copy Ninja Kakashi, Kakashi of the Sharingan",Male,Grey,2.0,320.0,Black,September 15,O,"Adults, Anti-Gravity Hair, Beastmasters, Exoti...",37602,1042,Kakashi is a jounin ninja from Konoha who is k...,https://www.anime-planet.com/characters/kakash...,38644.0,34566.0
2,348,348,Light YAGAMI,Kira,Male,Brown,4.0,9.0,Brown,"February 28, 1986",A,"Analytical, Big Ego, Charismatic, God Complex,...",29513,9110,"Armed with the power of Ryuk's Death Note, Lig...",https://www.anime-planet.com/characters/light-...,38623.0,1535.0
3,279,279,Naruto UZUMAKI,Unknown,Male,Blonde,6.0,20.0,Blue,October 10,B,"Beastmasters, Face Markings, Headbands, Hot-He...",28299,5792,Naruto is a young ninja with a single dream: t...,https://www.anime-planet.com/characters/naruto...,34091.0,35072.0
4,103,103,Edward ELRIC,Fullmetal Alchemist,Male,Blonde,3.0,306.0,Yellow,Unknown,Unknown,"Alchemists, Arm Blades, Artificial Limbs, Brai...",32568,1074,Known as a prodigy and one of the strongest al...,https://www.anime-planet.com/characters/edward...,33642.0,121.0

In [6]:
anime_data.head()

,MAL_ID,Name,Score,Genres,English name,Japanese name,Type,Episodes,Aired,Premiered,...,Score-10,Score-9,Score-8,Score-7,Score-6,Score-5,Score-4,Score-3,Score-2,Score-1
0,1,Cowboy Bebop,8.78,"Action, Adventure, Comedy, Drama, Sci-Fi, Space",Cowboy Bebop,カウボーイビバップ,TV,26,"Apr 3, 1998 to Apr 24, 1999",Spring 1998,...,229170.0,182126.0,131625.0,62330.0,20688.0,8904.0,3184.0,1357.0,741.0,1580.0
1,5,Cowboy Bebop: Tengoku no Tobira,8.39,"Action, Drama, Mystery, Sci-Fi, Space",Cowboy Bebop:The Movie,カウボーイビバップ 天国の扉,Movie,1,"Sep 1, 2001",Unknown,...,30043.0,49201.0,49505.0,22632.0,5805.0,1877.0,577.0,221.0,109.0,379.0
2,6,Trigun,8.24,"Action, Sci-Fi, Adventure, Comedy, Drama, Shounen",Trigun,トライガン,TV,26,"Apr 1, 1998 to Sep 30, 1998",Spring 1998,...,50229.0,75651.0,86142.0,49432.0,15376.0,5838.0,1965.0,664.0,316.0,533.0
3,7,Witch Hunter Robin,7.27,"Action, Mystery, Police, Supernatural, Drama, ...",Witch Hunter Robin,Witch Hunter ROBIN (ウイッチハンターロビン),TV,26,"Jul 2, 2002 to Dec 24, 2002",Summer 2002,...,2182.0,4806.0,10128.0,11618.0,5709.0,2920.0,1083.0,353.0,164.0,131.0
4,8,Bouken Ou Beet,6.98,"Adventure, Fantasy, Shounen, Supernatural",Beet the Vandel Buster,冒険王ビィト,TV,52,"Sep 30, 2004 to Sep 29, 2005",Fall 2004,...,312.0,529.0,1242.0,1713.0,1068.0,634.0,265.0,83.0,50.0,27.0

In [8]:
characters_dropped = characters_data[['ID', 'Gender', 'Hair Color', 'Tags', 'MAL_ID']]
characters_desc = characters_data[['ID', 'Description', 'MAL_ID']]

In [9]:
anime_dropped = anime_data[['MAL_ID', 'Genres', 'Type', 'Aired', 'Source']]

In [10]:
df_INNER_JOIN = pd.merge(characters_dropped, anime_dropped, left_on='MAL_ID', right_on='MAL_ID', how='inner')
df_INNER_JOIN.head()

,ID,Gender,Hair Color,Tags,MAL_ID,Genres,Type,Aired,Source
0,0,Male,Black,"Analytical, Barefoot, Detectives, Eye Bags, Sw...",1535.0,"Mystery, Police, Psychological, Supernatural, ...",TV,"Oct 4, 2006 to Jun 27, 2007",Manga
1,348,Male,Brown,"Analytical, Big Ego, Charismatic, God Complex,...",1535.0,"Mystery, Police, Psychological, Supernatural, ...",TV,"Oct 4, 2006 to Jun 27, 2007",Manga
2,155,Male,Black,"Agents of the Afterlife, Anti-Gravity Hair, Im...",1535.0,"Mystery, Police, Psychological, Supernatural, ...",TV,"Oct 4, 2006 to Jun 27, 2007",Manga
3,238,Female,Blonde,"Hyperactive, Idols, Pigtails",1535.0,"Mystery, Police, Psychological, Supernatural, ...",TV,"Oct 4, 2006 to Jun 27, 2007",Manga
4,180,Male,White,"Analytical, Detectives, Teenagers",1535.0,"Mystery, Police, Psychological, Supernatural, ...",TV,"Oct 4, 2006 to Jun 27, 2007",Manga